### ISSUE TITLE
the `uses' attribute must be a path, a Docker image, or owner/repo@ref

### ISSUE THREAD

**Issue by lfoppiano** [f3d-app/lfs-data-cache-action#4]
I've tried your action plugin on a simple Github action script and I've got the following error message:

```
Error
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```

my full script is this: 

```
name: Build unstable

on: [push]

concurrency: 
  group: unstable


jobs:
  #----------------------------------------------------------------------------
  # Cache LFS: Checkout LFS data and update the cache to limit LFS bandwidth
  #----------------------------------------------------------------------------
  cache_lfs:
    runs-on: ubuntu-latest
    name: Update LFS data cache
    outputs:
      lfs_sha: ${{ steps.lfs_sha_recover.outputs.lfs_sha }}
    steps:

      # Checkout your repository WITHOUT LFS
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'source'
          fetch-depth: 1
          lfs: false

      # Use producer action to recover the LFS data and upload it as cache/artifacts
      - name: Cache LFS Data
        id: lfs_sha_recover
        uses: f3d-app/lfs-data-cache-action:v1

  build:
    needs: cache_lfs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # disabled: 3.9, '3.11', '3.12'
        python-version: [ '3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'source'
          fetch-depth: 0
          lfs: false
      - name: Recover LFS Data
        uses: f3d-app/lfs-data-cache-action:v1
        with:
          workflow_label: 'consumer'
          lfs_sha: ${{ needs.cache_lfs.outputs.lfs_sha}}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Cleanup more disk space
        run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make install
          make install-for-tests
      - name: Lint with ruff
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
```
